# Generated by Django 2.2.7 on 2019-11-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
